-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgF13FSw6QNarhXpnV
3AIsSGvpRZo0Rl3jjAKKcNSrI7egCgYIKoZIzj0DAQehRANCAARQ3RR8b48ErKSU
eTEJWIN1E/U/UU18SdPlViyQFGEmNBGcRZwPazecEwgZSxXsqhxr9rWhIJ79zxtR
STcy/axQ
-----END PRIVATE KEY-----