const courselist = {
  "CH 222": "Applied Organic Chemistry",
  "CH 224": "Group Theory",
  "CH 211": "Industrial Chemistry",
  "CH 233": "Spectroscopic Techniques in Chemistry",
  "CH 223": "Chemical Technology Lab - I (Organic)",
  "CH 332": "Computational Chemistry",
  "CH 335": "Application of Nanomaterials",
  "CH 323": "Polymer Chemistry",
  "CH 334": "Chemical Technology Lab - III (Physical)",
  "CH 418": "Biological Chemistry of Metal Ions",
  "CH 428": "Drug Design and Development",
  "CH 438": "Application to Statistical Mechanics to Chemistry",
  "CH 437": "Chemical Approaches to Nanoscale Science and Technology",
  "CH 499": "Project - II",
  "CH 400": "Computers and Chemistry",
  "CH 411": "Inorganic Reaction Mechanism and Organometallics",
  "CH 421": "Organic Reactions Mechanisms",
  "CH 425": "Organic Chemistry Laboratory",
  "CH 432": "Chemical Dynamics and Electrochemistry",
  "CH 433": "Applications of Spectroscopy",
  "CH 500": "Graduate Seminar",
  "CH 600": "Project",
  "CH 612": "Inorganic Clusters",
  "CH 613": "Applied Inorganic Chemistry",
  "CH 623": "Supramolecular Chemistry",
  "CH 621": "Modern Reagents in Organic Synthesis",
  "CH 631": "Advanced Quantum Chemistry",
  "CH 639": "Principles and Applications of Molecular Fluorescence",
  "CH 618": "Bio-inorganic Chemistry",
  "CH 627": "New Reagents for Organic Synthesis",
  "CH 629": "Advances in Bio-organic Chemistry",
  "CH 617": "Organometallics",
  "CH 625": "Advances in Biological Macromolecules",
  "DA 243": "Introduction to Optimization",
  "DA 221": "Introduction to  Artificial Intelligence",
  "DA 213": "Python Programming Laboratory",
  "DA 215": "Database Management  Systems Laboratory",
  "DA 244": "Applied Probability and  Random Processes",
  "DA 221M": "Artificial Intelligence",
  "DA 323": "Multi-modal Data Processing and Learning - II",
  "DA 324": "Data Mining",
  "DA 325": "Deep Learning",
  "DA 352": "Privacy and Information Security",
  "DA 312": "Advanced Machine Learning Laboratory",
  "DA 353": "Internet of Things",
  "DA 332": "Data Visualization",
  "DA 322M": "Deep Learning",
  "DA 674": "Advanced Topics in Reinforcement Learning",
  "MA 002": "Preparatory Mathematics   II",
  "MA 102": "Mathematics - 2",
  "MA 224": "Real Analysis",
  "MA 252": "Design and Analysis of Algorithms",
  "MA 271": "Financial Engineering   I",
  "MA 322": "Scientific Computing",
  "MA 351": "Theory of Computation",
  "MA 373": "Financial Engineering   II",
  "MA 374": "Financial Engineering Laboratory",
  "MA 212M": "Mathematical Statistics",
  "MA 312M": "Modern Algebra",
  "MA 499": "Project II",
  "MA 642": "Real Analysis-1",
  "ME 101": "Engineering Mechanics",
  "ME 503": "Technical Writing",
  "ME 221": "Fluid Mechanics II",
  "ME 222": "Manufacturing Technology I",
  "ME 223": "Solid Mechanics II",
  "ME 224": "Kinematics of Machinery",
  "ME 321": "Applied Thermodynamics",
  "ME 322": "Machine Design",
  "ME 323": "Mechanical Measurements",
  "ME 324": "Industrial Engineering and Operations Reseach.",
  "ME 325": "Control Systems",
  "ME 202Mn": "Thermodynamics",
  "ME 511": "Engineering Materials and Characterization",
  "ME 513": "Physics of Deformation Processes",
  "ME 522": "Convective Heat Transfer",
  "ME 541": "Continuum Mechanics",
  "ME 542": "Numerical Analysis",
  "ME 553": "Gas Dynamics",
  "ME 554": "Rocket Propulsion",
  "ME 505": "MTP Phase II",
  "ME 607": "Introduction to Composite Materials",
  "ME 608": "Computer Aided Design-Computer Aided Manufacturing",
  "ME 615": "Rotor Dynamics",
  "ME 617": "Manufacturing of Polymers and Polymer Composites",
  "ME 619": "Fundamentals of Microfluidics",
  "ME 622": "Fundamentals of Fusion Energy Generation and Tokamaks",
  "ME 623": "Dynamics of Machining Processes",
  "ME 640": "Robotics and Robot Application",
  "ME 670": "Advanced Computational Fluid Dynamics",
  "ME 682": "Nonlinear Finite Element Methods",
  "ME 683": "Computational Gas Dynamics",
  "ME 688": "Advanced machining processes",
  "ME 692": "Gear Engineering",
  "ME 225": "Mechanical Workshop II",
  "ME 226": "Mechanical Engineering Lab II",
  "ME 326": "Mechanical Engineering Lab IV",
  "ME 515": "Manufacturing Laboratory",
  "ME 544": "Computational Mechanics Laboratory",
  "ME 499": "Project-II",
  "DA 526": "Image Processing with Machine Learning",
  "DA 531": "Data Visualization Lab",
  "DA 499": "BTP Project II",
  "MA 512": "Data Structures and Algorithms",
  "MA 542": "Differential Equations",
  "MA 548": "Ordinary Differential Equations",
  "MA 547": "Complex Analysis",
  "MA 625": "Linear Algebra-I",
  "MA 590": "Probability Theory",
  "MA 571": "Numerical Linear Algebra",
  "MA 573": "Numerics of Partial Differential Equations",
  "MA 588": "R Programming Lab",
  "MA 617": "Design and Analysis of Algorithms",
  "MA 619": "Data Structures Lab",
  "MA 654": "Advanced Data Structures and Algorithms",
  "MA 653": "Network Science",
  "MA 622": "Galois Theory",
  "MA 601": "Graphs and Matrices",
  "MA 641": "Operator Theory in Hilbert Spaces",
  "MA 690": "Understanding Statistical Learning Theory",
  "MA 591": "Optimization Techniques",
  "MA 324": "Statistical Inference and Multivariate Analysis",
  "MA 549": "Topology",
  "MA 599": "Project",
  "MA 640": "Topology and Calculus of Surfaces",
  "MA 662": "Differential Equations",
  "MA 621": "Rings and Modules",
  "MA 561": "Fluid Dynamics",
  "DD 111": "Forms, Order and Structure",
  "DD 112": "Principles of Visual Design",
  "DD 113": "Visualization and Illustrations",
  "DD 212": "Visual Narratives",
  "DD 213": "Art and Aesthetics in Design",
  "DD 214": "Design Workshop",
  "DD 215": "Cognitive Ergonomics",
  "MA 671": "Finite Element Methods for Partial Differential Equations",
  "RT 515": "Natural Resources Management",
  "ME 110": "Workshop I",
  "ME 552": "Aircraft Propulsion",
  "RT 514": "Water Resources Management",
  "RT 517": "Agri-horticultural Produce Processing Technology",
  "RT 512": "Livelihood and Entrepreneurship",
  "RT 520": "Field Work and Communication",
  "DA 214": "Database Management Systems",
  "EE 102": "Basic Electronics Lab",
  "EE 206": "Analog Circuits",
  "EE 230": "Probability and Random Processes",
  "EE 250": "Control Systems",
  "EE 252": "Measurement and Instrumentation",
  "EE 213M": "Digital Circuits",
  "EE 322M": "Signal Processing",
  "EE 521": "Digital Signal Processing Lab",
  "EE 522": "Statistical Signal Processing",
  "EE 525": "Advanced Topics in Machine Learning",
  "EE 512": "Analog IC Design",
  "EE 515": "Foundation of VLSI architectures",
  "EE 516": "System hardware design",
  "EE 517": "Analog VLSI Lab",
  "EE 562": "Power Electronics Applications in Power Systems",
  "EE 572": "Power Engineering Laboratory",
  "EE 580": "Electrical Machines and Drive Systems",
  "EE 553": "Optimal Control",
  "EE 554": "Nonlinear Systems and Control",
  "EE 555": "Automation Laboratory",
  "EE 533": "Wireless Communications",
  "CS 205": "Formal Languages, Automata Theory, and Computation",
  "EE 535": "Data Communication Network",
  "CS 207": "Design and Analysis of Algorithms",
  "EE 536": "Wireless Communications Design Lab",
  "EE 540": "Advance Electromagnetic Theory  and  Antennas",
  "CS 223": "Computer Architecture and Organization",
  "EE 548": "RF Laboratory",
  "EE 549": "Photonics Integrated Circuits",
  "EE 527": "Machine Learning Laboratory",
  "EE 526": "Machine Learning",
  "CS 224": "Hardware Lab",
  "CS 245": "Database Management Systems",
  "CS 246": "Database Management Systems Lab",
  "CS 206M": "Datastructures and Algorithms",
  "EE 335": "Information Theory & Coding",
  "EE 337": "Fundamentals of Wireless Communications",
  "EE 339": "Blockchain Science and Technology",
  "CS 110": "Computing Laboratory",
  "CS 101": "Introduction to Computing",
  "CS 345": "Software Engineering",
  "CS 346": "Software Engineering Lab",
  "CS 348": "Implementation of Programming Languages Lab",
  "CS 361": "Machine Learning",
  "CS 350M": "Computer Systems",
  "CS 558": "Computer Systems Lab",
  "CS 699": "Project II",
  "CS 331": "Programming Languages Lab",
  "CS 564": "Computational Complexity",
  "CS 533": "ML for Electronic Design Automation",
  "CS 527": "Parallel Computer Architecture",
  "PH 456": "Physics of Carbon-Based Materials",
  "PH 458": "Applied superconductivity",
  "PH 462": "Quantum Technology and Phenomena in Macroscopic systems",
  "PH 464": "Fundamentals of cosmology",
  "PH 466": "Advanced Statistical Mechanics",
  "PH 523": "Magnetism and Superconductivity",
  "PH 527": "Nanostructured Materials",
  "PH 531": "Laser Physics",
  "PH 541": "Quantum computation & Quantum information",
  "PH 544": "High Energy Physics",
  "PH 002": "Preparatory Course",
  "PH 102": "Physics 2",
  "PH 202": "Electromagnetics",
  "PH 204": "Quantum Mechanics-I",
  "PH 206": "Computational Physics",
  "PH 208": "Digital electronics & microprocessors",
  "PH 302": "Solid state physics",
  "PH 304": "Measurement techniques",
  "PH 306": "Lasers and Ultra Fast Optics",
  "PH 308": "Nuclear Science and Engineering",
  "PH 382M": "Laser Physics and Technology",
  "PH 402": "Mathematical Physics-II",
  "PH 404": "Statistical Mechanics",
  "PH 408": "Measurement techniques",
  "PH 410": "Electrodynamics-I",
  "PH 702": "Statistical methods in Condensed Matter Physics",
  "PH 704": "Guided and Fourier Wave Optics",
  "PH 706": "Gravitation and Cosmology",
  "PH 110": "Physics Laboratory",
  "PH 210": "General Physics Laboratory-I",
  "PH 310": "Advance Physics Laboratory",
  "PH 412": "General Physics Laboratory-I",
  "PH 516": "Advance Physics Laboratory",
  "HS 232M": "Linguistic Analysis",
  "EE 602": "Adaptive and Learning-based Control",
  "EE 611": "Organic Semiconductor Devices",
  "EE 621": "Computer Vision",
  "EE 632": "Advanced Topics in Communication Systems",
  "EE 606": "Power semiconductor devices",
  "EE 622": "Biomedical Signal Processing",
  "EE 656": "Robust Control",
  "EE 624": "Speech Technology",
  "EE 643": "Silicon Photonics",
  "EE 659": "Fuzzy Logic and Neural Networks",
  "EE 661": "Power Electronics for Renewable Energy Systems",
  "EE 607": "Information Theory",
  "EE 665": "Power Electronic Systems for Electric Vehicles",
  "EE 692": "Detection and Estimation Theory",
  "EE 605": "Machine Learning Architectures",
  "EE 619": "Semiconductor material and device characterization",
  "CS 579": "Automata, Logic and Games",
  "CS 499": "Project II",
  "EE 390": "Data structure and algorithms",
  "BT 101": "Introductory Biology",
  "BT 206": "Microbiology",
  "BT 207": "Genetic Engineering",
  "BT 208": "Transport Phenomenon in Bioprocesses",
  "BT 209": "Bioreaction Engineering",
  "BT 211": "Basic Biotechnology Lab",
  "BT 305": "Computational Biology",
  "BT 306": "Bioseparation Engineering",
  "BT 307": "Biological Data Analysis",
  "BT 308": "Bioengineering",
  "BT 608": "Microbial Biotechnology",
  "BT 601": "Analytical Biotechnology",
  "BT 502": "Quantitative Biology",
  "BT 504": "Biomolecular and Cellular Process Engineering",
  "BT 520": "Applied Biology and Bioengineering Lab",
  "BT 522": "Advanced Bioengineering",
  "BT 523": "Metabolic Engineering",
  "BT 524": "Bioinstrumentation & Control",
  "BT 540": "Applied Bioengineering Lab",
  "BT 607": "Plant Biotechnology",
  "BT 609": "Bioprocess Engineering",
  "BT 616": "Molecular Virology",
  "BT 619": "Essentials of Genetics",
  "BT 631": "Protein Structure, Function and Crystallography",
  "BT 630": "Physical Cell Biology",
  "BT 632": "Stem Cells, Cancer and Therapy",
  "BT 638": "Cellular And Molecular Aspects of Aging",
  "BT 617": "Proteomics: Methods & Applications",
  "EE 676": "Advanced Power System Monitoring",
  "EE 614": "Modern Display Technologies",
  "EE 338": "Advanced Analog Circuits",
  "HS 503": "Sociology of Development",
  "HS 517": "Comparative Politics of Developing Countries",
  "HS 699": "Dissertation",
  "HS 563": "Early Womens Writing in English",
  "HS 567": "Cultural Studies: Key Concepts and Theories",
  "HS 562": "International Relations and Diplomacy",
  "HS 569": "Language, Mind and Thought",
  "HS 561": "Historical Studies",
  "HS 559": "Indian Literary Theory",
  "HS 523": "Economic Development: Theory and Practice",
  "HS 697": "Project II",
  "HS 524": "Qualitative Research Methods in Social Sciences",
  "HS 556": "Introduction to Literary Studies",
  "HS 551": "Foundational Linguistics",
  "HS 552": "Critical Reasoning",
  "HS 722": "Cultural Anthropology",
  "HS 731": "Heritage, Identity and Archaeology",
  "HS 706": "Topics in Economics",
  "HS 751": "Advanced Public Economics",
  "HS 704": "Crossing Cultures",
  "HS 727": "Issues in Historical Research",
  "HS 781": "Approaches to Diplomatic and Military History",
  "HS 726": "History of Assam",
  "HS 733": "Issues in Phonological Theory",
  "HS 736": "Approaches to Prosodic Structure",
  "HS 749": "Issues in Tone Languages",
  "HS 784": "Acoustic Analyses of Tone Languages",
  "HS 734": "Perspectives in Linguistics",
  "HS 769": "RESEARCH METHODS IN LINGUISTICS",
  "HS 771": "Key Texts in Modern Political Thought",
  "HS 753": "Topics in International Relations",
  "BT 642": "Alternative Splicing and Diseases",
  "PH 455": "Microwave Theory and Application",
  "PH 459": "Nonlinear Fiber optics and applications",
  "PH 521": "Topics in Condensed Matter Physics",
  "PH 525": "Optoelectronics Materials and Devices",
  "EE 313": "Microelectronics Laboratory",
  "EE 332": "Digital Communication",
  "EE 333": "Communication and DSP Laboratory",
  "EE 334": "Computer networks",
  "EE 360": "Power Electronics",
  "EE 370": "Electrical Power Systems",
  "EE 371": "Advanced Electrical Engg Lab",
  "EE 381": "Electrical Machines Lab",
  "EE 557": "Optimization",
  "EE 595H": "Stochastic Models",
  "EE 596H": "Optimization Techniques",
  "CL 205": "Mass Transfer Operations I",
  "CL 206": "Solid Fluid Operations",
  "CL 207": "Computer Aided Numerical Methods",
  "CL 208": "Chemical Reaction Engineering I",
  "CL 209": "Process Equipment Design I",
  "CL 210H": "Laboratory 1: Fluid Mechanics",
  "CL 211H": "Laboratory 2: Heat Transfer",
  "CL 304": "Chemical Process Technology",
  "CL 305": "Transport Phenomena",
  "CL 306": "Process Engineering & Economics",
  "CL 312": "Computer Aided Process Equipmen Design",
  "CL 313": "Laboratory 4: Mass Transfer",
  "CL 314H": "Laboratory 5: Reaction Engineering",
  "CL 315H": "Laboratory 6: Process Control",
  "CL 399": "General Learning of Chemical Engineering Research Project - II",
  "CL 499": "Project II",
  "CL 503": "Advanced Thermodynamics",
  "CL 504": "Advanced reaction Engineering",
  "CL 505": "Petroleum Production Engineering",
  "CL 506": "Smart Materials",
  "CL 514": "Fundamentals of Material Science & Engineering",
  "CL 653": "Applications of Artificial Intelligence and Machine Learning in Chemical Engineering",
  "CL 654": "Multiscale Modelling and Simulation",
  "CL 598": "Petroleum Laboratory",
  "CL 599": "Scientific Communications",
  "CL 612": "Colloid and Interface Science",
  "CL 613": "Computational Fluid Dynamics",
  "CL 617": "Petrochemicals",
  "CL 619": "Refinery process design",
  "CL 622": "Molecular simulations: Principles and Applications",
  "CL 625": "Fundamentals of micro-nanofluidics & microfabrication",
  "CL 633": "Applied Statistical Thermodynamics",
  "CL 640": "Research Methodology and Scientific Writing",
  "CL 650": "Quantum technologies in chemcial engineering",
  "CL 699": "PROJECT II",
  "IFST 018": "Joint Degree Dissertation",
  "IFST 020": "Joint Degree Dissertation",
  "EE 640": "Introduction to Electronic Systems Packaging",
  "EE 207": "Analog Circuits Laboratory",
  "EE 253": "Instrumentation Laboratory",
  "EE 396": "Design Lab",
  "EE 399": "BTP II (New Curriculum)",
  "EE 499": "B. Tech Project-IV",
  "DD 220M": "Introduction to Ergonomics",
  "DD 216.": "Typography and Grid Systems",
  "DD 311": "Systems approach to Design",
  "DD 312": "Design Evaluation Methods",
  "DD 324": "(PD) Plastics & Composites",
  "DD 325": "(VC) Graphic Communication",
  "DD 326": "(TD) Introduction to Automobile Design",
  "DD 398": "BDes Project II",
  "DD 320M": "Product Planning and Strategy",
  "DD 411": "Design and Entrepreneurship",
  "DD 499": "BDes Project IV",
  "DD 505": "Form Studies",
  "DD 506": "Graphic Design",
  "DD 507": "Design Project",
  "DD 605": "Thesis Project (Phase II)",
  "DD 546": "Product Form and Structures",
  "DD 547": "Design for Environmental Sustainability",
  "DD 548": "Embodiment Design",
  "DD 549": "Systems thinking",
  "DD 610": "Project (Phase II)",
  "BM 511H": "Corporate Finance",
  "BM 512H": "Computer-aided Operations Research",
  "BM 513H": "Business Communication",
  "BM 514H": "Organization Structure and Design",
  "BM 515H": "Strategic Management",
  "BM 650H": "Sales and Distribution Management",
  "BM 628H": "Personality and Assessment",
  "BM 622H": "HR Analytics",
  "BM 666H": "Quality Management and Control",
  "DD 705": "Design Research Methods",
  "DD 709": "Design-based Project",
  "DD 607": "Creativity and Innovation",
  "PH 406": "Quantum Mechanics-II",
  "DA 651": "Artificial Intelligence for Next-Generation Wireless Systems",
  "CL 656": "Chemical Process Safety",
  "DD 558": "Design for Social Innovation",
  "DD 559": "Design for Additive Manufacturing (DfAM)",
  "DD 509": "Interaction Design",
  "DD 517": "Automobile Design",
  "DD 523": "Creative Furniture Design",
  "DD 606": "Product Detailing",
  "DD 532": "Motion Graphics",
  "DD 712": "Problem-based Learning through Design",
  "DD 554": "Pattern Recognition and Machine Learning",
  "DD 533": "Auditory and Voice User Interaction Design",
  "DD 537": "Introduction to Service Design",
  "MA 575": "Mathematical Methods",
  "CE 206": "Geotechnical Engineering",
  "CE 215": "Geotechnical Engineering Laboratory",
  "CE 222": "Environmental Engineering I",
  "CE 223": "Environmental Engineering I Lab",
  "CE 220": "Hydraulics and Hydraulic Structures",
  "CE 221": "Hydraulics and Hydraulic Structures Laboratory",
  "CE 205": "Structural Analysis I",
  "CE 201": "Surveying",
  "CE 213": "Surveying Laboratory",
  "CE 308": "Construction Technology and Management",
  "CE 320": "Engineering Hydrology",
  "CE 321": "Hydrology Laboratory",
  "CE 309": "Design of Steel Structures",
  "CE 324": "Mathematical Concepts and Applications in Civil Engineering",
  "CE 322": "Transportation Engineering II",
  "CE 323": "Transportation Engineering II - Laboratory",
  "CE 649": "Ground improvement techniques",
  "CE 648": "Applied Soil Mechanics",
  "CE 504": "Advanced Structural Design",
  "CE 606": "Earthquake Engineering",
  "CE 594": "Geohazards Science and Engineering",
  "CE 595": "Advanced Techniques in Geosciences",
  "CE 646": "Rock Mechanics",
  "CE 524": "Biological Process in Environmental Engineering",
  "CE 525": "Solids and Hazardous Waste",
  "CE 664": "Industrial Wastewater Pollution Control",
  "CE 533": "Advance Foundation Engineering",
  "CE 618": "Mechanics of Unsaturated Soils",
  "CE 647": "Environmental Geotechnology",
  "CE 534": "Seminar Course",
  "CE 510": "Quality and Safety Management in Construction",
  "CE 544": "Project Management Laboratory",
  "CE 612": "Advanced Concrete Technology",
  "CE 614": "Financing Infrastructure Projects",
  "CE 620": "Advanced Quantitative Techniques in Construction Management",
  "CE 511": "Analysis and Design of Bridges",
  "CE 609": "Computation Plasticity",
  "CE 615": "Design of Masonry Structures",
  "CE 675": "Wind Turbine Analysis and Design",
  "CE 583": "Pavement Analysis and Design",
  "CE 584": "Traffic Engineering",
  "CE 585": "Credit Seminar",
  "CE 624": "Highway construction practise",
  "CE 623": "Pavement Evaluation, Rehabilitation and Maintenance",
  "CE 628": "Traffic Flow Modelling and Simulation",
  "CE 552": "Water Resources Systems Analysis, planning & Management",
  "CE 564": "Stochastic Hydrology",
  "CE 556": "Subsurface Hydrology",
  "CE 562": "Transient Flow Analysis",
  "CE 499": "BTP Phase II",
  "CE 691": "M Tech Project  II",
  "CE 550": "Project and Thesis Phase II",
  "CE 695": "M Tech Project  II",
  "CE 699": "Project and Thesis Phase II",
  "CE 693": "Project and Thesis Phase II",
  "CE 697": "Project and Dissertation",
  "CE 599": "M Tech Project Phase II",
  "CE 573": "Seismic Evaluation and Retrofitting of Structures",
  "RT 692": "Project Phase - II",
  "CS 556": "Performance Modeling, Analysis and Evaluation",
  "HT 603": "Advanced Immunology",
  "CE 668": "Applied seismology",
  "HT 601": "Medical Diagnostic Devices, BioMEMS, and Biosensors",
  "MA 592": "Mathematical Finance",
  "HT 602": "Regulatory Affairs of Biomedical Devices",
  "HT 506": "Biotechniques and Bioinstrumentation Laboratory",
  "HT 509": "Regenerative Medicine and Stem Cells Laboratory",
  "DA 623": "Computing with Signals",
  "ME 613": "Nonlinear Vibration",
  "ME 696": "Biomedical Devices and Systems",
  "BT 624": "Fluorescence Techniques in Biotechnology",
  "BT 633": "Human Biology and Diseases",
  "BT 635": "Chemo Informatics",
  "CL 643": "Computer aided applied optimization",
  "CL 611": "Advanced Process Control",
  "HS 720": "Cultural Theory and Interpretation",
  "HS 715": "Seminar course (Psychology)",
  "HS 752": "Positive Psychology",
  "HS 525": "India",
  "HS 631": "Food and Culture in Contemporary Society",
  "HS 632": "Social Epistemology of Science",
  "HS 633": "Religion and Modernity",
  "HS 634": "Rhetoric in Western Science Writing",
  "CE 537": "Removal and Recovery of Contaminants from Wastewater",
  "CH 644": "Applied Quantum Chemistry",
  "HT 511": "Stem Cells and Therapeutics",
  "HT 507": "Diagnostics & Devices Laboratory",
  "HT 508": "Product Design and Prototyping Laboratory",
  "EE 699": "MTP Phase II",
  "SP 697": "Project -I",
  "SP 699": "Project -III",
  "EN 697": "Project 1",
  "DT 603": "Scientific Exploration and Investigation by Drones",
  "EN 699": "Project 3",
  "EN 206": "Heat and Mass Transfer",
  "EN 207": "Biomass, Biofuels and Biorefinery",
  "EN 208": "Control and Instrumentation",
  "EN 209": "Energy and Sustainability",
  "EN 210": "Thermo-Fluid and Heat Transfer Laboratory",
  "EN 211": "Community Engagement and Entrepreneurship Program",
  "EN 307": "Materials Science for Energy Applications",
  "EN 308": "Solar Energy Technology",
  "EN 309": "Numerical Methods",
  "EN 310": "Energy Economics and Auditing",
  "EN 312": "Solar Energy Laboratory",
  "EN 313": "Energy Materials and Device Fabrication Laboratory",
  "EN 674": "Energy Economics, Planning and Management",
  "BT 699": "M. Tech Project II (MTP II)",
  "BT 701": "M. Tech Project II (MTP II)",
  "BT 402": "BTech Project-II",
  "PH 708": "Mini project",
  "BM 530H": "Project Work-II",
  "PH 422": "Project-II",
  "PH 518": "Project-II",
  "HT 599": "Project - II",
  "EM 599": "Project phase 3",
  "SA 210": "SA 210",
  "SA 217": "SA 217",
  "SA 110": "SA 110",
  "SA 203": "SA 203",
  "SA 107": "SA 107",
  "SA 105": "SA 105",
  "SA 106": "SA 106",
  "SA 103": "SA 103",
  "SA 216": "SA 216",
  "SA 207": "SA 207",
  "SA 104": "SA 104",
  "SA 201": "SA 201",
  "SA 206": "SA 206",
  "SA 205": "SA 205",
  "SA 101": "SA 101",
  "SA 102": "SA 102",
  "SA 202": "SA 202",
  "SA 116": "SA 116",
  "SA 204": "SA 204",
  "DM 503": "Hazards monitoring and prediction",
  "DM 504": "Research methodology and field visit",
  "DM 515": "Rehabilitation and Retrofitting of RC Structures",
  "DM 697": "Project Phase 1",
  "DM 699": "Project (Phase 3)",
  "HT 510": "Tissue Engineering and Regenerative Medicine",
  "EN 671": "Solar Energy Conversion Technology",
  "RT 691": "Project Phase I",
  "CS 528": "High Performance Computing",
  "MA 618": "Mathematics for Computer Science",
  "ME 657": "Two Phase Flow and Heat Transfer",
  "RA 505": "Robot Sensing and Vision",
  "RA 506": "Machine Learning",
  "RA 607": "Underactuated systems",
  "RA 599": "Project Phase - II",
  "CE 698": "Project and Thesis Phase I",
  "MA 684": "Advanced Probability",
  "DS 699": "MTP Project-II",
  "EN 681": "Automotive Vehicles",
  "ME 502": "Engineering Computing Laboratory",
  "ME 532": "Finite Element Methods in Engineering",
  "ME 521": "Conduction and Radiation",
  "ME 531": "Mechanical Vibrations",
  "MA 646": "Advanced Operator Theory",
  "RA 507": "Technical Writing",
  "HS 200": "Sustainable Development Goals",
  "HS 755": "Introduction to Econometrics",
  "CE 570": "River Engineering",
  "HS 163": "Basic Econometrics",
  "HS 115": "Leadership And Communication in Historical Drama",
  "HS 116": "Sociology of India: Conformities and Contradictions",
  "HS 121": "Understanding Psychology: Individual and Work Settings",
  "HS 125": "Introductory Macroeconomics",
  "HS 134": "Introduction to Archaeology",
  "HS 136": "Introduction to Indian Constitution and Political Processes",
  "HS 138": "Psychology of Well Being",
  "HS 139": "The Short Story: Theory and Perspectives",
  "HS 148": "Development and its Discontents",
  "HS 155": "Introductory Mathematical Economics",
  "HS 156": "Economics of Health and Education",
  "HS 212": "Public Economics",
  "HS 218": "Ecology and Society",
  "HS 257": "Ethnography of Speaking",
  "HS 229": "Environmental Economics",
  "HS 232": "Economics of Climate Change",
  "HS 233": "History of Contemporary India",
  "HS 235": "Writing Systems of the World",
  "HS 240": "Literature and Science Writing",
  "HS 248": "Indian Literary Theory",
  "HS 251": "Social Choice and Welfare",
  "CH 419": "Consumer Chemistry",
  "EE 626": "Pattern Recognition and Machine Learning",
  "EE 633": "Error Control Codes",
  "PH 465": "Optoelectronics",
  "CE 610": "Computational Structural Mechanics",
  "CS 561": "Artificial Intelligence",
  "CE 616": "Blast and Impact Resistant Design",
  "PH 441": "Quantum Computation and Cryptography"
}

export default courselist;