const courses = [
  {"name": "molecular biotechnology", "code": "bt202m"},
  {"name": "microbiology", "code": "bt206"},
  {"name": "genetic engineering", "code": "bt207"},
  {"name": "transport phenomenon in bioprocesses", "code": "bt208"},
  {"name": "bioreaction engineering", "code": "bt209"},
  {"name": "basic biotechnology lab", "code": "bt211"},
  {"name": "computational biology", "code": "bt305"},
  {"name": "bioseparation engineering", "code": "bt306"},
  {"name": "biological data analysis", "code": "bt307"},
  {"name": "bioengineering", "code": "bt308"},
  {"name": "btech project-ii", "code": "bt402"},
  {"name": "human biology and diseases", "code": "bt403"},
  {"name": "metagenomics", "code": "bt411"},
  {"name": "enzymology", "code": "bt412"},
  {"name": "bioenvironmental engineering", "code": "bt416"},
  {"name": "drug design and discovery", "code": "bt420"},
  {"name": "quantitative biology", "code": "bt502"},
  {"name": "biomolecular and cellular process engineering", "code": "bt504"},
  {"name": "applied biology and bioengineering lab", "code": "bt520"},
  {"name": "analytical biotechnology", "code": "bt601"},
  {"name": "gene therapy", "code": "bt605"},
  {"name": "microbial biotechnology", "code": "bt608"},
  {"name": "bioprocess engineering", "code": "bt609"},
  {"name": "essentials of genetics (open elective)", "code": "bt619"},
  {
    "name": "advances in plant genetic engineering and functional genomics",
    "code": "bt621"
  },
  {"name": "biofuels", "code": "bt622"},
  {"name": "physical cell biology (open elective)", "code": "bt630"},
  {"name": "animal models in biomedical research", "code": "bt634"},
  {"name": "nmr spectroscopy: principles and applications", "code": "bt639"},
  {"name": "neural imaging and signal systems", "code": "bt640"},
  {"name": "biointerface engineering", "code": "bt643"},
  {"name": "m. tech project ii (mtp ii)", "code": "bt699"},
  {"name": "quantum chemistry of atoms and molecules", "code": "bt651"},
  {"name": "surveying", "code": "ce201"},
  {"name": "structural analysis i", "code": "ce205"},
  {"name": "geotechnical engineering", "code": "ce206"},
  {"name": "surveying laboratory", "code": "ce213"},
  {"name": "geotechnical engineering laboratory", "code": "ce215"},
  {"name": "hydraulics and hydraulic structures", "code": "ce220"},
  {"name": "hydraulics and hydraulic structures laboratory", "code": "ce221"},
  {"name": "environmental engineering i", "code": "ce222"},
  {"name": "environmental engineering i lab", "code": "ce223"},
  {
    "name": "infrastrcture and transportation systems planning",
    "code": "ce252m"
  },
  {"name": "construction technology and management", "code": "ce308"},
  {"name": "design of steel structures", "code": "ce309"},
  {"name": "engineering hydrology", "code": "ce320"},
  {"name": "hydrology laboratory", "code": "ce321"},
  {"name": "transportation engineering ii", "code": "ce322"},
  {"name": "transportation engineering ii - laboratory", "code": "ce323"},
  {
    "name": "mathematical concepts and applications in civil engineering",
    "code": "ce324"
  },
  {"name": "advanced structural design", "code": "ce504"},
  {"name": "quality and safety management in construction", "code": "ce510"},
  {"name": "analysis and design of bridges", "code": "ce511"},
  {"name": "plates, shells and elastic stability", "code": "ce514"},
  {"name": "biological process in environmental engineering", "code": "ce524"},
  {"name": "solids and hazardous waste", "code": "ce525"},
  {"name": "advance foundation engineering", "code": "ce533"},
  {"name": "seminar course", "code": "ce534"},
  {"name": "project management laboratory", "code": "ce544"},
  {
    "name": "water resources systems analysis, planning & management",
    "code": "ce552"
  },
  {"name": "principles of water quality and eia", "code": "ce555"},
  {"name": "subsurface hydrology", "code": "ce556"},
  {
    "name": "watershed management and remote sensing applications",
    "code": "ce559"
  },
  {"name": "pavement analysis and design", "code": "ce583"},
  {"name": "traffic engineering", "code": "ce584"},
  {"name": "credit seminar", "code": "ce585"},
  {"name": "geohazards science and engineering", "code": "ce594"},
  {"name": "advanced techniques in geosciences", "code": "ce595"},
  {"name": "earthquake engineering", "code": "ce606"},
  {"name": "random vibration", "code": "ce607"},
  {"name": "reliability based structural design", "code": "ce608"},
  {"name": "computational structural mechanics", "code": "ce610"},
  {"name": "advanced concrete technology", "code": "ce612"},
  {"name": "financing infrastructure projects", "code": "ce614"},
  {"name": "design of masonry structures", "code": "ce615"},
  {"name": "mechanics of unsaturated soils", "code": "ce618"},
  {"name": "traffic flow modelling and simulation", "code": "ce628"},
  {
    "name": "pavement evaluation, rehabilitation and maintenance",
    "code": "ce623"
  },
  {"name": "highway construction practise", "code": "ce624"},
  {"name": "subsurface invstigation and instrumentation", "code": "ce642"},
  {"name": "rock mechanics", "code": "ce646"},
  {"name": "industrial wastewater pollution control", "code": "ce664"},
  {
    "name": "water distribution and wastewater collection system design",
    "code": "ce665"
  },
  {"name": "industrial chemistry", "code": "ch211"},
  {"name": "applied organic chemistry", "code": "ch222"},
  {"name": "chemical technology lab - i (organic)", "code": "ch223"},
  {"name": "group theory", "code": "ch224"},
  {"name": "spectroscopic techniques in chemistry", "code": "ch233"},
  {"name": "polymer chemistry", "code": "ch323"},
  {"name": "computational chemistry", "code": "ch332"},
  {"name": "chemical technology lab - iii (physical)", "code": "ch334"},
  {"name": "application of nanomaterials", "code": "ch335"},
  {"name": "computers and chemistry", "code": "ch400"},
  {"name": "inorganic reaction mechanism and organometallics", "code": "ch411"},
  {"name": "biological chemistry of metal ions", "code": "ch418"},
  {"name": "consumer chemistry", "code": "ch419"},
  {"name": "organic reactions mechanisms", "code": "ch421"},
  {"name": "organic chemistry laboratory", "code": "ch425"},
  {"name": "drug design and development", "code": "ch428"},
  {"name": "chemical dynamics and electrochemistry", "code": "ch432"},
  {"name": "applications of spectroscopy", "code": "ch433"},
  {
    "name": "chemical approaches to nanoscale science and technology",
    "code": "ch437"
  },
  {
    "name": "application to statistical mechanics to chemistry",
    "code": "ch438"
  },
  {"name": "project - ii", "code": "ch499"},
  {"name": "graduate seminar", "code": "ch500"},
  {"name": "project", "code": "ch600"},
  {"name": "concepts of molecular machine", "code": "ch603"},
  {"name": "applied inorganic chemistry", "code": "ch613"},
  {"name": "organometallics", "code": "ch617"},
  {"name": "bio-inorganic chemistry", "code": "ch618"},
  {"name": "modern reagents in organic synthesis", "code": "ch621"},
  {"name": "supramolecular chemistry", "code": "ch623"},
  {"name": "new reagents for organic synthesis", "code": "ch627"},
  {"name": "advances in bio-organic chemistry", "code": "ch629"},
  {"name": "a fundamental approach to physical chemistry", "code": "ch636"},
  {
    "name": "principles and applications of molecular fluorescence",
    "code": "ch639"
  },
  {"name": "applied quantum chemistry", "code": "ch644"},
  {"name": "mass transfer operations i", "code": "cl205"},
  {"name": "solid fluid operations", "code": "cl206"},
  {"name": "computer aided numerical methods", "code": "cl207"},
  {"name": "chemical reaction engineering i", "code": "cl208"},
  {"name": "process equipment design i", "code": "cl209"},
  {"name": "laboratory 1: fluid mechanics", "code": "cl210h"},
  {"name": "laboratory 2: heat transfer", "code": "cl211h"},
  {"name": "chemical process technology", "code": "cl304"},
  {"name": "transport phenomena", "code": "cl305"},
  {"name": "process engineering & economics", "code": "cl306"},
  {"name": "computer aided process equipmen design", "code": "cl312"},
  {"name": "laboratory 4: mass transfer", "code": "cl313"},
  {"name": "laboratory 5: reaction engineering", "code": "cl314h"},
  {"name": "laboratory 6: process control", "code": "cl315h"},
  {"name": "advanced thermodynamics", "code": "cl503"},
  {"name": "advanced reaction engineering", "code": "cl504"},
  {"name": "petroleum production engineering", "code": "cl505"},
  {"name": "smart materials", "code": "cl506"},
  {"name": "fundamentals of material science & engineering", "code": "cl514"},
  {"name": "petroleum laboratory", "code": "cl598"},
  {"name": "scientific communications", "code": "cl599"},
  {"name": "colloid and interface science", "code": "cl612"},
  {"name": "computational fluid dynamics", "code": "cl613"},
  {"name": "optimization techniques", "code": "cl615"},
  {"name": "refinery process design", "code": "cl619"},
  {
    "name": "molecular simulations: principles and applications",
    "code": "cl622"
  },
  {
    "name": "fundamentals of micro-nanofluidics & microfabrication",
    "code": "cl625"
  },
  {"name": "energy resources", "code": "cl626"},
  {"name": "multiphase flow", "code": "cl627"},
  {"name": "catalysis and adsorbents", "code": "cl628"},
  {"name": "applied rheology", "code": "cl634"},
  {"name": "microelectronic fabrication", "code": "cl636"},
  {"name": "research methodology and scientific writing", "code": "cl640"},
  {"name": "computer aided applied optimization", "code": "cl643"},
  {"name": "quantum technologies in chemcial engineering", "code": "cl650"},
  {"name": "foundations of data science for engineers", "code": "cl651"},
  {
    "name": "formal languages, automata theory, and computation",
    "code": "cs205"
  },
  {"name": "datastructures and algorithms", "code": "cs206m"},
  {"name": "design and analysis of algorithms", "code": "cs207"},
  {"name": "computer architecture and organization", "code": "cs223"},
  {"name": "hardware lab", "code": "cs224"},
  {"name": "database management systems", "code": "cs245"},
  {"name": "database management systems lab", "code": "cs246"},
  {"name": "programming languages lab", "code": "cs331"},
  {"name": "software engineering", "code": "cs345"},
  {"name": "software engineering lab", "code": "cs346"},
  {"name": "implementation of programming languages lab", "code": "cs348"},
  {"name": "computer systems", "code": "cs350m"},
  {"name": "machine learning", "code": "cs361"},
  {"name": "hierarchical memory algorithms", "code": "cs506"},
  {"name": "optimization methods", "code": "cs508"},
  {"name": "high performance computing", "code": "cs528"},
  {"name": "topics and tools in social media data mining", "code": "cs529"},
  {"name": "approximation algorithms", "code": "cs534"},
  {"name": "topics in networks", "code": "cs544"},
  {"name": "computer and network security", "code": "cs549"},
  {"name": "computer systems lab", "code": "cs558"},
  {"name": "c based vlsi design", "code": "cs577"},
  {"name": "data visualization lab", "code": "cs595"},
  {"name": "introduction to reinforcement learning", "code": "da671"},
  {"name": "image processing with machine learning", "code": "da526"},
  {"name": "introduction to statistical learning", "code": "da546"},
  {"name": "visual narratives", "code": "dd212"},
  {"name": "art and aesthetics in design", "code": "dd213"},
  {"name": "design workshop", "code": "dd214"},
  {"name": "cognitive ergonomics", "code": "dd215"},
  {"name": "introduction to ergonomics", "code": "dd220m"},
  {"name": "typography and grid systems", "code": "dd303"},
  {"name": "systems approach to design", "code": "dd311"},
  {"name": "design evaluation methods", "code": "dd312"},
  {"name": "product planning and strategy", "code": "dd320m"},
  {"name": "animation fundamentals", "code": "dd322"},
  {"name": "(pd) plastics & composites", "code": "dd324"},
  {"name": "(vc) graphic communication", "code": "dd325"},
  {"name": "(td) introduction to automobile design", "code": "dd326"},
  {"name": "bdes project ii", "code": "dd398"},
  {"name": "design and entrepreneurship", "code": "dd411"},
  {"name": "bdes project iv", "code": "dd499"},
  {"name": "form studies", "code": "dd505"},
  {"name": "graphic design", "code": "dd506"},
  {"name": "design project", "code": "dd507"},
  {"name": "interaction design", "code": "dd509"},
  {
    "name": "collaborative design methods in new product development",
    "code": "dd514"
  },
  {
    "name": "digital human modelling and simulation in product design",
    "code": "dd516"
  },
  {"name": "automobile design", "code": "dd517"},
  {"name": "graphic design studio", "code": "dd524"},
  {"name": "motion graphics", "code": "dd 532"},
  {"name": "thesis project (phase ii)", "code": "dd605"},
  {"name": "product detailing", "code": "dd 606"},
  {"name": "design-based project", "code": "dd709"},
  {"name": "research-based project", "code": "dd710"},
  {"name": "hazards monitoring and prediction", "code": "dm503"},
  {"name": "research methodology and field visit", "code": "dm504"},
  {"name": "financing for disaster risk reduction (drr)", "code": "dm514"},
  {"name": "rehabilitation and retrofitting of rc structures", "code": "dm515"},
  {"name": "analog circuits", "code": "ee206"},
  {"name": "analog circuits laboratory", "code": "ee207"},
  {"name": "digital circuits", "code": "ee213m"},
  {"name": "probability and random processes", "code": "ee230"},
  {"name": "control systems", "code": "ee250"},
  {"name": "measurement and instrumentation", "code": "ee252"},
  {"name": "instrumentation laboratory", "code": "ee253"},
  {"name": "microelectronics laboratory", "code": "ee313"},
  {"name": "flexible and printable electronics", "code": "ee314"},
  {"name": "signal processing", "code": "ee322m"},
  {"name": "digital communication", "code": "ee332"},
  {"name": "communication and dsp laboratory", "code": "ee333"},
  {"name": "computer networks", "code": "ee334"},
  {"name": "information theory & coding", "code": "ee335"},
  {"name": "advanced control system", "code": "ee352"},
  {"name": "power electronics", "code": "ee360"},
  {"name": "electrical power systems", "code": "ee370"},
  {"name": "advanced electrical engg lab", "code": "ee371"},
  {"name": "electrical machines lab", "code": "ee381"},
  {"name": "data structure and algorithms", "code": "ee390"},
  {"name": "btp ii (new curriculum)", "code": "ee399"},
  {"name": "btp phase - ii", "code": "ee499"},
  {"name": "analog ic design", "code": "ee512"},
  {"name": "vlsi system design", "code": "ee515"},
  {"name": "vlsi dsp", "code": "ee516"},
  {"name": "vlsi lab-ii", "code": "ee517"},
  {"name": "vlsi lab-iii", "code": "ee518"},
  {"name": "digital signal processing lab", "code": "ee521"},
  {"name": "statistical signal processing", "code": "ee522"},
  {"name": "advanced topics in machine learning", "code": "ee525"},
  {"name": "machine learning laboratory", "code": "ee527"},
  {"name": "wireless communications", "code": "ee533"},
  {"name": "communication system design lab", "code": "ee534"},
  {"name": "data communication network", "code": "ee535"},
  {"name": "antennas, rf and microwave laboratory", "code": "ee541"},
  {"name": "computational electromagnetics", "code": "ee543"},
  {"name": "photonics devices and circuits", "code": "ee544"},
  {"name": "optimal control", "code": "ee553"},
  {"name": "nonlinear systems and control", "code": "ee554"},
  {"name": "automation laboratory", "code": "ee555"},
  {"name": "power electronics applications in power systems", "code": "ee562"},
  {"name": "power engineering laboratory", "code": "ee572"},
  {"name": "electrical machines and drive systems", "code": "ee580"},
  {"name": "detection and estimation theory", "code": "ee592"},
  {"name": "stochastic models", "code": "ee595h"},
  {"name": "organic semiconductor devices", "code": "ee611"},
  {"name": "radio frequency integrated circuits", "code": "ee613"},
  {"name": "computer vision", "code": "ee621"},
  {"name": "biomedical signal processing", "code": "ee622"},
  {"name": "biometrics", "code": "ee627"},
  {"name": "error control codes", "code": "ee633"},
  {
    "name": "mimo wireless communications: fundamentals and advances",
    "code": "ee634"
  },
  {"name": "silicon photonics", "code": "ee643"},
  {
    "name": "mathematical techniques for control and signal processing",
    "code": "ee655"
  },
  {"name": "robust control", "code": "ee656"},
  {"name": "power electronics for renewable energy systems", "code": "ee661"},
  {"name": "synchrophasor technology", "code": "ee674"},
  {"name": "introduction to parallel computing", "code": "ee 694"},
  {"name": "power electronic systems for electric vehicles", "code": "ee665"},
  {"name": "mtp phase ii", "code": "ee699"},
  {"name": "solar energy conversion technology", "code": "en671"},
  {"name": "energy economics, planning and management", "code": "en674"},
  {"name": "project 1", "code": "en697"},
  {"name": "project 3", "code": "en699"},
  {"name": "problems of philosophy", "code": "hs107"},
  {"name": "cognitive psychology", "code": "hs113"},
  {"name": "sociology of science", "code": "hs119"},
  {"name": "game theory and economics", "code": "hs123"},
  {"name": "introductory macroeconomics", "code": "hs125"},
  {"name": "introduction to archaeology", "code": "hs134"},
  {"name": "topics in bilingualism", "code": "hs135"},
  {
    "name": "introduction to indian constitution and political processes",
    "code": "hs136"
  },
  {"name": "psychology of well being", "code": "hs138"},
  {"name": "the short story: theory and perspectives", "code": "hs139"},
  {"name": "development and its discontents", "code": "hs148"},
  {"name": "social history of technology in modern india", "code": "hs217"},
  {"name": "ecology and society", "code": "hs218"},
  {"name": "management of organization behaviour", "code": "hs221"},
  {"name": "philosophy of science", "code": "hs222"},
  {"name": "environmental economics", "code": "hs229"},
  {"name": "linguistic analysis", "code": "hs232m"},
  {"name": "history of contemporary india", "code": "hs233"},
  {"name": "writing systems of the world", "code": "hs235"},
  {"name": "economics of uncertainty and information", "code": "hs239"},
  {"name": "literature and science writing", "code": "hs240"},
  {"name": "transboundary waters: conflict and cooperation", "code": "hs242"},
  {"name": "indian business history", "code": "hs244"},
  {"name": "social choice and welfare", "code": "hs245"},
  {"name": "literature and film: the word and the image", "code": "hs320m"},
  {"name": "sociology of development", "code": "hs503"},
  {"name": "comparative politics of developing countries", "code": "hs517"},
  {"name": "economic development: theory and practice", "code": "hs523"},
  {"name": "qualitative research methods in social sciences", "code": "hs524"},
  {"name": "india's development: issues and debates", "code": "hs525"},
  {"name": "development and finance", "code": "hs604"},
  {"name": "sociology of gender", "code": "hs606"},
  {"name": "dissertation", "code": "hs699"},
  {"name": "invisible exchanges", "code": "hs707"},
  {"name": "introduction to western philosophy", "code": "hs712"},
  {
    "name": "understanding organizational behaviour: theory and research",
    "code": "hs714"
  },
  {"name": "research methodology in psychology", "code": "hs716"},
  {"name": "philosophy of religion", "code": "hs719"},
  {"name": "history in indian vernaculars", "code": "hs724"},
  {"name": "issues in historical research", "code": "hs727"},
  {"name": "heritage, identity and archaeology", "code": "hs731"},
  {"name": "issues in cultural studies", "code": "hs732"},
  {"name": "issues in phonological theory", "code": "hs733"},
  {"name": "perspectives in linguistics", "code": "hs734"},
  {"name": "experimental phonology", "code": "hs735"},
  {
    "name": "issues in applied ethics: a multicultural approach",
    "code": "hs740"
  },
  {"name": "issues in tone languages", "code": "hs749"},
  {"name": "topics in international relations", "code": "hs753"},
  {"name": "research methods in political science", "code": "hs763"},
  {"name": "key texts in modern political thought", "code": "hs771"},
  {"name": "bilingualism: language and cognition", "code": "hs768"},
  {"name": "understanding social movements", "code": "hs780"},
  {"name": "approaches to diplomatic and military history", "code": "hs781"},
  {"name": "acoustic analyses of tone languages", "code": "hs784"},
  {"name": "phonetics and speech", "code": "ls521"},
  {"name": "introduction to language science", "code": "ls551"},
  {"name": "joint degree dissertation i", "code": "ifst017"},
  {"name": "dissertation part iv", "code": "ifst020"},
  {"name": "mathematical statistics", "code": "ma212m"},
  {"name": "real analysis", "code": "ma224"},
  {"name": "financial engineering - i", "code": "ma271"},
  {"name": "modern algebra", "code": "ma312m"},
  {"name": "scientific computing", "code": "ma322"},
  {"name": "statistical inference and multivariate analysis", "code": "ma324"},
  {"name": "theory of computation", "code": "ma351"},
  {"name": "financial engineering - ii", "code": "ma373"},
  {"name": "financial engineering laboratory", "code": "ma374"},
  {"name": "financial risk management and modelling", "code": "ma477"},
  {"name": "combinatorics", "code": "ma510"},
  {"name": "data structures and algorithms", "code": "ma512"},
  {"name": "differential equations", "code": "ma542"},
  {"name": "complex analysis", "code": "ma547"},
  {"name": "mathematical modelling and numerical simulation", "code": "ma562"},
  {"name": "numerical linear algebra", "code": "ma571"},
  {"name": "numerics of partial differential equations", "code": "ma573"},
  {"name": "r programming lab", "code": "ma588"},
  {"name": "probability theory", "code": "ma590"},
  {"name": "queueing theory and applications", "code": "ma597"},
  {"name": "graphs and matrices", "code": "ma601"},
  {"name": "mathematics for computer science", "code": "ma618"},
  {"name": "data structures lab", "code": "ma619"},
  {"name": "rings and modules", "code": "ma621"},
  {"name": "introduction to algebraic geometry", "code": "ma 623"},
  {"name": "linear algebra - i", "code": "ma625"},
  {"name": "real analysis - i", "code": "ma642"},
  {"name": "introduction to c*-algebras", "code": "ma645"},
  {"name": "advanced course on hardy spaces", "code": "ma650"},
  {"name": "distributed algorithms", "code": "ma651"},
  {"name": "fourier analysis", "code": "ma746"},
  {"name": "mechatronics", "code": "me202m"},
  {"name": "fluid mechanics – i i (div-1)", "code": "me221"},
  {"name": "manufacturing technology – i (div-1)", "code": "me222"},
  {"name": "solid mechanics – ii (div-1)", "code": "me223"},
  {"name": "kinematics of machinery (div-1)", "code": "me224"},
  {"name": "mechanical workshop – ii (div-1)", "code": "me225"},
  {
    "name":
        "mechanical engineering lab – ii (div-1) (kinematics, data acquisition, turbomachinery)",
    "code": "me226"
  },
  {"name": "fundamentals of artificial intelligence", "code": "me302m"},
  {"name": "applied thermodynamics (div-1)", "code": "me321"},
  {"name": "machine design (div i)", "code": "me322"},
  {"name": "mechanical measurements (div i)", "code": "me323"},
  {"name": "industrial engineering and operations reseach.", "code": "me324"},
  {"name": "control systems (div i)", "code": "me325"},
  {
    "name":
        "mechanical engineering lab – iv (tribology, thermal science, instrumentation and control)",
    "code": "me326"
  },
  {"name": "engineering materials and characterization", "code": "me511"},
  {"name": "physics of deformation processes", "code": "me513"},
  {"name": "manufacturing laboratory", "code": "me515"},
  {"name": "convective heat transfer", "code": "me522"},
  {"name": "continuum mechanics", "code": "me541"},
  {"name": "numerical analysis", "code": "me542"},
  {"name": "computational mechanics laboratory", "code": "me544"},
  {"name": "aircraft propulsion", "code": "me552"},
  {"name": "gas dynamics", "code": "me553"},
  {"name": "rocket propulsion", "code": "me554"},
  {"name": "fracture, fatigue and failure analysis", "code": "me605"},
  {"name": "introduction to composite materials", "code": "me607"},
  {"name": "nuclear energy: concepts and applications", "code": "me612"},
  {"name": "rotor dynamics", "code": "me615"},
  {"name": "fundamentals of microfluidics", "code": "me619"},
  {"name": "refrigeration and air-conditioning", "code": "me621"},
  {"name": "additive manufacturing", "code": "me628"},
  {"name": "viscous fluid flow", "code": "me648"},
  {"name": "two phase flow and heat transfer", "code": "me657"},
  {"name": "sports biomechanics", "code": "me664"},
  {"name": "soft computing for engineers", "code": "me674"},
  {"name": "computational gas dynamics", "code": "me683"},
  {"name": "advanced machining processes", "code": "me688"},
  {"name": "recent advances in nanotechnology", "code": "nt705"},
  {"name": "electromagnetics", "code": "ph202"},
  {"name": "quantum mechanics-i", "code": "ph204"},
  {"name": "computational physics", "code": "ph206"},
  {"name": "digital electronics & microprocessors", "code": "ph208"},
  {"name": "general physics laboratory-i", "code": "ph210"},
  {"name": "engineering optics", "code": "ph282m"},
  {"name": "solid state physics", "code": "ph302"},
  {"name": "measurement techniques", "code": "ph304"},
  {"name": "lasers and ultra fast optics", "code": "ph306"},
  {"name": "nuclear science & technology", "code": "ph308"},
  {"name": "advance physics laboratory", "code": "ph310"},
  {"name": "mini project", "code": "ph312"},
  {"name": "laser physics", "code": "ph382m"},
  {"name": "mathematical physics-ii", "code": "ph402"},
  {"name": "statistical mechanics", "code": "ph404"},
  {"name": "quantum mechanics-ii", "code": "ph406"},
  {"name": "electrodynamics-i", "code": "ph410"},
  {"name": "project-ii", "code": "ph422"},
  {"name": "theory and simulation of nanostructures", "code": "ph442"},
  {"name": "plasma physics", "code": "ph451"},
  {"name": "magnetic recording", "code": "ph452"},
  {"name": "applied superconductivity", "code": "ph458"},
  {"name": "fundamentals of cosmology", "code": "ph464"},
  {"name": "advanced statistical mechanics", "code": "ph466"},
  {"name": "thin film phenomena", "code": "ph524"},
  {"name": "nanostructured materials", "code": "ph527"},
  {"name": "quantum computation & quantum information", "code": "ph541"},
  {"name": "high energy physics", "code": "ph544"},
  {"name": "nonlinear dynamics and chaos", "code": "ph551"},
  {"name": "statistical methods in condensed matter physics", "code": "ph702"},
  {"name": "guided & fourier wave optics", "code": "ph704"},
  {"name": "gravitation and cosmology", "code": "ph706"},
  {"name": "robot sensing and vision", "code": "ra505"},
  {"name": "livelihood and entrepreneurship", "code": "rt512"},
  {"name": "water resources management", "code": "rt514"},
  {"name": "natural resources management", "code": "rt515"},
  {
    "name":
        "product and process development in food & bioprocessing industries",
    "code": "rt516"
  },
  {"name": "agri-horticulture produce processing technology", "code": "rt517"},
  {"name": "field work and communication", "code": "rt520"},
  {"name": "project phase - ii", "code": "rt692"},
  {"name": "microeconomics", "code": "bm501h"},
  {"name": "financial systems", "code": "bm502h"},
  {"name": "marketing management", "code": "bm503h"},
  {
    "name": "business statistics and data analysis for\nmanagement",
    "code": "bm504h"
  },
  {"name": "organizational behaviour", "code": "bm505h"},
  {"name": "biochemical process calculations", "code": "bt201"},
  {"name": "essentials of biochemistry", "code": "bt201m"},
  {"name": "bio-thermodynamics", "code": "bt202"},
  {"name": "biochemistry", "code": "bt203"},
  {"name": "genetics", "code": "bt204"},
  {"name": "cell and molecular biology", "code": "bt205"},
  {"name": "biophysics", "code": "bt301"},
  {"name": "cellular biotechnology", "code": "bt301m"},
  {"name": "bioinformatics", "code": "bt302"},
  {"name": "biochemical engineering", "code": "bt303"},
  {"name": "immunology", "code": "bt304"},
  {"name": "biochemical engineering lab", "code": "bt311"},
  {"name": "analytical biotechnology lab", "code": "bt312"},
  {"name": "b.tech project i", "code": "bt401"},
  {"name": "biotechniques", "code": "bt501"},
  {"name": "advanced genetic engineering", "code": "bt503"},
  {"name": "advanced bioreactor engineering", "code": "bt521"},
  {"name": "experimental techniques in\nbioengineering", "code": "bt530"},
  {"name": "m.tech seminar", "code": "bt600"},
  {"name": "food biotechnology", "code": "bt606"},
  {"name": "systems biology", "code": "bt612"},
  {"name": "concepts and methods in proteomics", "code": "bt617"},
  {"name": "biomaterials", "code": "bt618"},
  {"name": "biosensors", "code": "bt620"},
  {"name": "research methodology", "code": "bt623"},
  {"name": "genome editing and engineering", "code": "bt637"},
  {"name": "introduction to ipr and ethics", "code": "bt645"},
  {"name": "m. tech project i (mtp i)", "code": "bt698"},
  {"name": "solid mechanics", "code": "ce202"},
  {"name": "fluid mechanics", "code": "ce203"},
  {"name": "engineering geology", "code": "ce207"},
  {"name": "engineering geology lab", "code": "ce208"},
  {"name": "civil engineering materials", "code": "ce211"},
  {"name": "civil engineering materials laboratory", "code": "ce212"},
  {"name": "fluid mechanics lab", "code": "ce214"},
  {"name": "structural analysis ii", "code": "ce302"},
  {"name": "geotechnical engg. ii", "code": "ce303"},
  {"name": "transportation engg. i", "code": "ce304"},
  {"name": "reinforced concrete design", "code": "ce305"},
  {"name": "geotechnical engineering ii lab", "code": "ce313"},
  {"name": "transportation engineering i lab", "code": "ce314"},
  {"name": "environmental engineering ii", "code": "ce316"},
  {"name": "dynamic of structure", "code": "ce411"},
  {"name": "prestressed concrete and industrial\nstructures", "code": "ce415"},
  {"name": "bridge engineering", "code": "ce416"},
  {"name": "solid waste engineeing", "code": "ce445"},
  {"name": "b tech project-i", "code": "ce498"},
  {"name": "finite element methods", "code": "ce502"},
  {"name": "structural dynamics", "code": "ce503"},
  {"name": "structural engineering laboratory", "code": "ce512"},
  {
    "name": "process chemistry for water and\nwastewater treatment",
    "code": "ce521"
  },
  {
    "name": "physico chemical processes in\nenvironmental engineering",
    "code": "ce522"
  },
  {"name": "air and noise pollution", "code": "ce523"},
  {"name": "design of environmental engineering\nsystems", "code": "ce527"},
  {"name": "advanced soil mechanics", "code": "ce531"},
  {"name": "dynamics of soil and foundations", "code": "ce532"},
  {"name": "infrastructure planning", "code": "ce541"},
  {
    "name": "project management in infrastructure construction",
    "code": "ce542"
  },
  {
    "name":
        "infrastructure projects - construction methods and equipment management",
    "code": "ce543"
  },
  {"name": "project and thesis phase-i", "code": "ce549"},
  {"name": "surface water hydrology", "code": "ce551"},
  {"name": "advanced hydraulic engineering", "code": "ce553"},
  {"name": "advanced fluid mechanics", "code": "ce554"},
  {"name": "stochastic hydrology", "code": "ce564"},
  {"name": "sediment dynamics in fluvial systems", "code": "ce567"},
  {"name": "urban transportation systems planning", "code": "ce581"},
  {"name": "pavement materials", "code": "ce582"},
  {"name": "expansive soil", "code": "ce587"},
  {"name": "earth system dynamics", "code": "ce591"},
  {"name": "exploration geoscience", "code": "ce592"},
  {"name": "advanced remote sensing", "code": "ce593"},
  {"name": "mtech project- phase i", "code": "ce598"},
  {"name": "numerical methods", "code": "ce601"},
  {"name": "elastic analysis in geotechnical\nengineering", "code": "ce644"},
  {"name": "geotechnical practice for waste\ndisposal", "code": "ce650"},
  {"name": "road safety engineering", "code": "ce651"},
  {"name": "precision remote sensing", "code": "ce652"},
  {"name": "advanced mathematics for engineers", "code": "ce669"},
  {"name": "project & thesis phase i", "code": "ce692"},
  {"name": "mtech project-i", "code": "ce694"},
  {"name": "project and thesisphase - i", "code": "ce696"},
  {"name": "inorganic chemistry", "code": "ch212"},
  {"name": "organic chemistry", "code": "ch221"},
  {"name": "introduction to quantum chemistry", "code": "ch231"},
  {"name": "environmental chemistry", "code": "ch301"},
  {"name": "technical report presentation", "code": "ch302"},
  {"name": "chemical technology lab ii", "code": "ch314"},
  {"name": "frontiers of coordination chemistry", "code": "ch316"},
  {"name": "chemical kinetics and electrochemistry", "code": "ch331"},
  {"name": "modern chemical technology", "code": "ch401"},
  {"name": "chemistry of p- and d-block elements", "code": "ch410"},
  {"name": "organometallic chemistry", "code": "ch417"},
  {"name": "principles of organic chemistry", "code": "ch420"},
  {"name": "green chemistry and technology", "code": "ch426"},
  {"name": "medicinal chemistry", "code": "ch427"},
  {"name": "petroleums and petrochemicals", "code": "ch429"},
  {"name": "quantum chemistry", "code": "ch430"},
  {"name": "group theory and spectroscopy", "code": "ch431"},
  {"name": "physical chemistry laboratory", "code": "ch435"},
  {"name": "project - i", "code": "ch498"},
  {"name": "principles of bioinorganic chemistry", "code": "ch511"},
  {"name": "inorganic chemistry laboratory", "code": "ch515"},
  {"name": "concepts in organic synthesis", "code": "ch520"},
  {"name": "bio-organic chemistry", "code": "ch521"},
  {"name": "classical and statistical\nthermodynamics", "code": "ch530"},
  {"name": "physical methods in chemistry", "code": "ch601"},
  {"name": "supramolecules: concepts and\napplications", "code": "ch614"},
  {"name": "art in organic synthesis", "code": "ch626"},
  {"name": "chemistry of biological macromolecules", "code": "ch628"},
  {"name": "chemical applications of group theory", "code": "ch633"},
  {"name": "time dependent quantum mechanics", "code": "ch634"},
  {"name": "computational methods in chemistry", "code": "ch637"},
  {"name": "scientific writing and presentation", "code": "ch645"},
  {"name": "chemical process calculation", "code": "cl201"},
  {"name": "chemical engineering thermodynamics", "code": "cl203"},
  {"name": "heat transfer", "code": "cl204"},
  {"name": "mass transfer ii", "code": "cl301"},
  {"name": "chemical reaction engineering - ii", "code": "cl302"},
  {"name": "process control and instrumentation", "code": "cl303"},
  {"name": "solid fluid operations laboratory", "code": "cl310"},
  {"name": "technical writing and presentation", "code": "cl311"},
  {
    "name": "general learning of chemical\nengineering research project - i",
    "code": "cl398"
  },
  {"name": "project i", "code": "cl498"},
  {"name": "advanced transport phenomena", "code": "cl501"},
  {"name": "petroleum reservoir engineering", "code": "cl511"},
  {"name": "petroleum refinery engineering", "code": "cl512"},
  {"name": "characterization of materials", "code": "cl513"},
  {"name": "advanced process control", "code": "cl611"},
  {"name": "fluidization engineering", "code": "cl614"},
  {"name": "polymer science and technology", "code": "cl623"},
  {"name": "membranes", "code": "cl629"},
  {"name": "composites materials", "code": "cl630"},
  {"name": "process intensification and integration", "code": "cl641"},
  {"name": "petroleum reservoir simulation", "code": "cl644"},
  {"name": "applied statistics for chemical engineers", "code": "cl645"},
  {"name": "polymer soft lithography", "code": "cl649"},
  {"name": "process modelling and simulation lab", "code": "cl652"},
  {"name": "discrete mathematics", "code": "cs201"},
  {"name": "algorithms and data structures", "code": "cs203"},
  {"name": "algorithms and data structures laboratory", "code": "cs204"},
  {"name": "theoretical foundations of computer science", "code": "cs205m"},
  {"name": "digital design", "code": "cs221"},
  {"name": "system software laboratory", "code": "cs242"},
  {"name": "digital logic and computer architecture", "code": "cs322m"},
  {"name": "introduction to nlp", "code": "cs323"},
  {"name": "computer networks laboratory", "code": "cs342"},
  {"name": "operating systems", "code": "cs343"},
  {"name": "operating systems lab.", "code": "cs344"},
  {"name": "computational geometry", "code": "cs502"},
  {"name": "advanced compiler", "code": "cs536"},
  {"name": "virtual and augmented reality systems", "code": "cs560"},
  {"name": "neural networks for nlp", "code": "cs563"},
  {"name": "speech processing", "code": "cs566"},
  {"name": "internet of things", "code": "cs578"},
  {"name": "deep learning", "code": "cs590"},
  {"name": "databases", "code": "cs592h"},
  {"name": "data structures and databases lab", "code": "cs593"},
  {"name": "python programming lab", "code": "cs594"},
  {"name": "mobile robotics", "code": "cs666"},
  {"name": "project 2", "code": "cs699"},
  {"name": "algorithms and data structure", "code": "da211"},
  {"name": "algorithms and data structure lab", "code": "da212"},
  {"name": "introduction to data science", "code": "da231"},
  {"name": "statistical foundations for data science", "code": "da241"},
  {"name": "mathematical foundations of data science", "code": "da241m"},
  {"name": "signals , systems & networks", "code": "da251"},
  {"name": "introduction to mathematical biology", "code": "da547"},
  {"name": "deep learning for computer vision", "code": "da621"},
  {"name": "data driven system theory", "code": "da672"},
  {"name": "machine learning in quantum physics", "code": "da771"},
  {"name": "introduction to design", "code": "dd101"},
  {"name": "representation techniques", "code": "dd102"},
  {"name": "elements of design", "code": "dd103"},
  {"name": "applied science for design", "code": "dd104"},
  {"name": "tinkering studio", "code": "dd105"},
  {"name": "photo and video communication", "code": "dd202"},
  {"name": "materials and processes", "code": "dd203"},
  {"name": "visual communication theory", "code": "dd204"},
  {"name": "ergonomics in design", "code": "dd205"},
  {"name": "user research methods", "code": "dd206"},
  {"name": "bdes project i", "code": "dd216"},
  {"name": "design analysis", "code": "dd302"},
  {"name": "tangible interfaces", "code": "dd304"},
  {"name": "product design", "code": "dd310m"},
  {"name": "modelling and simulation techniques", "code": "dd321"},
  {"name": "design management", "code": "dd401"},
  {"name": "design research and technical writing", "code": "dd402"},
  {"name": "design project iii", "code": "dd498"},
  {"name": "design - an introduction", "code": "dd501"},
  {"name": "visual design - principles and\napplications", "code": "dd502"},
  {"name": "ergonomics", "code": "dd503"},
  {"name": "design methods", "code": "dd504"},
  {
    "name": "product design prototyping and\nadvanced manufacturing",
    "code": "dd508"
  },
  {"name": "new media studies", "code": "dd512"},
  {"name": "typography", "code": "dd515"},
  {"name": "representation techniques for\nanimation", "code": "dd518"},
  {"name": "system design for sustainability", "code": "dd521"},
  {"name": "introduction to toy design", "code": "dd527"},
  {"name": "introduction to industrial design", "code": "dd542"},
  {"name": "product design methods", "code": "dd543"},
  {"name": "ergonomics in product design", "code": "dd544"},
  {"name": "rapid prototyping and development", "code": "dd545"},
  {"name": "image processing with machine\nlearning", "code": "dd550"},
  {"name": "biomedical devices", "code": "dd551"},
  {"name": "basics of signal processing", "code": "dd553"},
  {"name": "usability engineering", "code": "dd601"},
  {"name": "thesis project phase i", "code": "dd603"},
  {"name": "design research methods", "code": "dd705"},
  {"name": "fundamentals of disaster management", "code": "dm501"},
  {
    "name": "socio-economic and policy aspects of\ndisaster risk reduction",
    "code": "dm502"
  },
  {
    "name": "application of artificial intelligence for disaster management",
    "code": "dm511"
  },
  {"name": "project phase 2", "code": "dm698"},
  {"name": "mtp project - i", "code": "ds698"},
  {"name": "semiconductor devices", "code": "ee203"},
  {"name": "circuit theory", "code": "ee204"},
  {"name": "principles of electrical engineering", "code": "ee205"},
  {"name": "digital circuits laboratory", "code": "ee211"},
  {"name": "signals and systems", "code": "ee220"},
  {"name": "embedded systems", "code": "ee312"},
  {"name": "digital signal processing", "code": "ee321"},
  {"name": "principles of communication", "code": "ee331"},
  {"name": "electromagnetic theory", "code": "ee340"},
  {"name": "electromagnetic field theory", "code": "ee340m"},
  {"name": "control and robotics laboratory", "code": "ee351"},
  {"name": "electrical machines", "code": "ee380"},
  {"name": "btech project-i", "code": "ee398"},
  {"name": "communication systems", "code": "ee424m"},
  {"name": "semiconductor device modeling", "code": "ee510"},
  {"name": "semiconductor ic technology", "code": "ee511"},
  {"name": "vlsi lab i", "code": "ee513"},
  {"name": "digital ic design", "code": "ee514"},
  {"name": "photonics and microelectronics laboratory", "code": "ee519"},
  {"name": "signal processing algorithms and architectures", "code": "ee520"},
  {"name": "introduction to machine learning", "code": "ee523"},
  {"name": "communication system theory", "code": "ee530"},
  {"name": "communication system simulation lab", "code": "ee531"},
  {"name": "information theory", "code": "ee537"},
  {"name": "rf circuits and systems", "code": "ee542"},
  {"name": "photonics devices", "code": "ee547"},
  {"name": "linear systems theory", "code": "ee550"},
  {"name": "estimation and identification", "code": "ee551"},
  {"name": "applied control lab", "code": "ee552"},
  {"name": "linear algebra", "code": "ee556"},
  {"name": "power electronic converters", "code": "ee560"},
  {"name": "power electronics laboratory", "code": "ee561"},
  {"name": "modern power systems", "code": "ee570"},
  {"name": "insulation and high voltage engineering", "code": "ee571"},
  {"name": "linear algebra and optimization", "code": "ee590"},
  {"name": "probability and stochastic processes", "code": "ee591"},
  {"name": "fundamentals of vlsi cad", "code": "ee610"},
  {"name": "speech signal processing and coding", "code": "ee623"},
  {"name": "mobile communication", "code": "ee630"},
  {"name": "selected topics in information theory", "code": "ee636"},
  {"name": "massive mimo for 5g communications", "code": "ee638"},
  {"name": "plasmonic, nanophotonic and metamaterials", "code": "ee644"},
  {"name": "optical measurement techniques and applications", "code": "ee646"},
  {"name": "multivariable control theory", "code": "ee651"},
  {"name": "modeling and simulation of dynamic systems", "code": "ee653"},
  {
    "name": "modelling and control of power electronic converters",
    "code": "ee660"
  },
  {"name": "electrical power quality and reliability", "code": "ee672"},
  {"name": "advanced topics in random processes", "code": "ee693"},
  {"name": "data-driven system theory", "code": "ee695"},
  {"name": "introduction to quantum computing", "code": "ee696"},
  {"name": "project phase i", "code": "ee698"},
  {"name": "modelling, dynamics and control of evs", "code": "em502"},
  {"name": "renewable energy systems", "code": "en661"},
  {"name": "operation and instrumentation", "code": "en663"},
  {"name": "energy storage systems", "code": "en672"},
  {"name": "fundamentals of energy engineering", "code": "en673"},
  {"name": "distributed energy resources in electric\ngrid", "code": "en680"},
  {
    "name": "sociology of india: conformities and\ncontradictions",
    "code": "hs116"
  },
  {"name": "language, culture and cognition", "code": "hs120"},
  {"name": "economic theory: an introduction", "code": "hs129"},
  {"name": "introduction to phonetics", "code": "hs133"},
  {"name": "india's health system", "code": "hs142"},
  {"name": "drama from aristotle to goethe", "code": "hs144"},
  {"name": "war and peace: india's military history", "code": "hs147"},
  {"name": "consumer behaviour", "code": "hs149"},
  {"name": "cities", "code": "hs151"},
  {"name": "introductory mathematical economics", "code": "hs155"},
  {"name": "logical reasoning", "code": "hs160"},
  {"name": "sustainable development goals", "code": "hs200"},
  {"name": "sound structure of language and\nspeech analysis", "code": "hs211"},
  {"name": "public economics", "code": "hs212"},
  {"name": "psychology of health and adjustment", "code": "hs213"},
  {"name": "archaeological studies in ancient\ntechnology", "code": "hs219"},
  {
    "name": "inventing the truth: the art and craft of\nautobiography",
    "code": "hs225"
  },
  {"name": "comparative drama", "code": "hs231m"},
  {"name": "economics of climate change", "code": "hs232"},
  {"name": "sociological perspectives on modernity", "code": "hs236"},
  {"name": "contemporary literary theory", "code": "hs318m"},
  {"name": "language and thought", "code": "hs418m"},
  {"name": "essentials of political theory", "code": "hs501"},
  {"name": "agriculture and rural development", "code": "hs514"},
  {"name": "introduction to economics", "code": "hs515"},
  {"name": "the study of society", "code": "hs516"},
  {"name": "economic history of colonial india", "code": "hs519"},
  {
    "name": "region, nation and the making of post-\ncolonial india",
    "code": "hs521"
  },
  {
    "name": "quantitative research methods in social\nsciences",
    "code": "hs522"
  },
  {"name": "critical reasoning", "code": "hs552"},
  {"name": "theories and thinkers: the concept of\nculture", "code": "hs554"},
  {"name": "introduction to liberal studies", "code": "hs555"},
  {
    "name": "between history and memory : genres\nof life writing",
    "code": "hs558"
  },
  {"name": "race and the novel", "code": "hs560"},
  {"name": "modern political and social imaginaries", "code": "hs618"},
  {"name": "political economy of agrarian\ndevelopment", "code": "hs620"},
  {"name": "land, dispossession and development", "code": "hs624"},
  {"name": "casual interference in development economics", "code": "hs630"},
  {"name": "project phase 1", "code": "hs698"},
  {"name": "crossing cultures", "code": "hs704"},
  {"name": "topics in economics", "code": "hs706"},
  {"name": "research in cultural studies", "code": "hs721"},
  {"name": "cultural anthropology", "code": "hs722"},
  {"name": "methods in historical research", "code": "hs723"},
  {"name": "history of assam", "code": "hs726"},
  {"name": "sociological theory", "code": "hs729"},
  {"name": "research methods in sociology", "code": "hs730"},
  {"name": "approaches to prosodic structure", "code": "hs736"},
  {"name": "perspectives on science, technology\nand society", "code": "hs738"},
  {"name": "research methods in linguistics", "code": "hs769"},
  {
    "name": "development planning and official\nstatistics in india",
    "code": "hs774"
  },
  {"name": "the material text and its other", "code": "hs787"},
  {"name": "social epistemology", "code": "hss746"},
  {"name": "introduction to cellular processes", "code": "ht501"},
  {"name": "basic physiology for clinical immersion", "code": "ht502"},
  {
    "name": "introduction to biomedical electronics and instrumentation",
    "code": "ht503"
  },
  {"name": "basics of mathematical modelling and simulation", "code": "ht504"},
  {
    "name": "research methodology, ethics, ipr, entrepreneurship and biosafety",
    "code": "ht505"
  },
  {"name": "advanced food processing", "code": "ifst001"},
  {
    "name": "international joint exercises in food\nscience and technology",
    "code": "ifst002"
  },
  {
    "name": "international joint global internship &\nseminar-b",
    "code": "ifst003"
  },
  {"name": "design thinking and scientific writing", "code": "ifst005"},
  {"name": "multicomponent mass transfer", "code": "ifst008"},
  {
    "name": "biomolecular and cellular processing\nengineering",
    "code": "ifst009"
  },
  {"name": "plant biotechnology", "code": "ifst012"},
  {"name": "livelihood management and agro\ntechnology", "code": "ifst015"},
  {
    "name":
        "product and process development in food and bioprocessing industries",
    "code": "ifst016"
  },
  {"name": "dissertation part iia", "code": "ifst018"},
  {"name": "joint degree dissertation", "code": "ifst019"},
  {"name": "mathematics and statistics", "code": "ls501"},
  {"name": "data structure and programming", "code": "ls531"},
  {"name": "mathematics iii", "code": "ma201"},
  {"name": "elementary number theory and algebra", "code": "ma222"},
  {"name": "probability theory and random\nprocesses", "code": "ma225"},
  {"name": "data structures", "code": "ma251"},
  {"name": "optimization", "code": "ma321"},
  {"name": "monte carlo simulation", "code": "ma323"},
  {"name": "stochastic calculus for finance", "code": "ma372"},
  {"name": "differential geometry", "code": "ma411m"},
  {"name": "matrix computations", "code": "ma423"},
  {"name": "computational finance", "code": "ma473"},
  {"name": "project-i", "code": "ma498"},
  {"name": "graph theory", "code": "ma502"},
  {"name": "number theory and cryptography", "code": "ma506"},
  {"name": "computer programming", "code": "ma511"},
  {"name": "functional analysis", "code": "ma543"},
  {"name": "topology", "code": "ma549"},
  {"name": "measure theory", "code": "ma550"},
  {"name": "numerical computations lab", "code": "ma581"},
  {"name": "advanced statistical algorithms", "code": "ma691"},
  {"name": "seminar", "code": "ma697"},
  {"name": "theory of distribution and sobolev\nspaces", "code": "ma745"},
  {"name": "introduction to robotics", "code": "me201m"},
  {"name": "thermodynamics", "code": "me211"},
  {"name": "solid mechanics i", "code": "me212"},
  {"name": "engineering materials", "code": "me213"},
  {"name": "fluid mechanics - i", "code": "me214"},
  {"name": "machine drawing", "code": "me215"},
  {"name": "mechanical engg laboratary- i", "code": "me216"},
  {"name": "robotic vision and control", "code": "me301m"},
  {"name": "manufacturing technology ii", "code": "me312"},
  {"name": "dynamics of machinery", "code": "me313"},
  {"name": "design of machine elements", "code": "me314"},
  {"name": "mechanical engineering laboratory iii", "code": "me315"},
  {"name": "summer training", "code": "me401"},
  {"name": "btech project-iii", "code": "me498"},
  {"name": "advanced engineering mathematics", "code": "me501"},
  {"name": "engineering computing laboratory", "code": "me502"},
  {"name": "technical writing", "code": "me503"},
  {"name": "mtp phase i", "code": "me504"},
  {"name": "subtractive manufacturing", "code": "me510"},
  {"name": "welding and additive manufacturing", "code": "me512"},
  {"name": "conduction and radiation", "code": "me521"},
  {"name": "advanced mechanics of solids", "code": "me530"},
  {"name": "mechanical vibrations", "code": "me531"},
  {"name": "finite element methods in engineering", "code": "me532"},
  {"name": "introduction to aerospace engineering", "code": "me550"},
  {"name": "aerodynamics", "code": "me551"},
  {
    "name": "computer aided design-computer\naided manufacturing",
    "code": "me608"
  },
  {"name": "optimization methods in engineering", "code": "me609"},
  {"name": "robotics and robot application", "code": "me640"},
  {"name": "tribology of bearings", "code": "me659"},
  {"name": "theory of plate and shells", "code": "me676"},
  {"name": "mechanics of sheet metal forming", "code": "me678"},
  {"name": "mechanical behaviour of materials", "code": "me679"},
  {"name": "experimental method", "code": "me680"},
  {"name": "smart materials: modelling and\napplications", "code": "me689"},
  {
    "name": "nano device: fabrication,\nproductization and patent",
    "code": "nt601"
  },
  {
    "name": "laboratory safety and risk\nmanagement: principles",
    "code": "nt602"
  },
  {"name": "mathematical physics", "code": "ph201"},
  {"name": "classical mechanics", "code": "ph203"},
  {"name": "heat and thermodynamics", "code": "ph207"},
  {"name": "analog electronics", "code": "ph209"},
  {"name": "electronics laboratory -i", "code": "ph211"},
  {"name": "quantum mechanics ii", "code": "ph303"},
  {"name": "atomic and molecular spectroscopy", "code": "ph307"},
  {"name": "electronics lab-ii", "code": "ph309"},
  {"name": "math phy-i", "code": "ph401"},
  {"name": "computer programming and numerical\nmethods", "code": "ph407"},
  {"name": "electronics", "code": "ph409"},
  {"name": "electronics lab", "code": "ph411"},
  {"name": "nanoelectronics and nanophotonics", "code": "ph413"},
  {"name": "simulation techniques in physical\nsystems", "code": "ph415"},
  {"name": "materials science and engineering", "code": "ph419"},
  {"name": "solar cells : fundamentals and\napplications", "code": "ph448"},
  {"name": "electroceramics", "code": "ph460"},
  {"name": "electrodynamics ii", "code": "ph501"},
  {"name": "atomic and molecular physics", "code": "ph503"},
  {"name": "nuclear and particle physics", "code": "ph507"},
  {"name": "project-1", "code": "ph509"},
  {"name": "general physics laboratory ii", "code": "ph511"},
  {"name": "physics of semiconductors", "code": "ph522"},
  {"name": "quantum optics", "code": "ph536"},
  {"name": "quantum field theory", "code": "ph543"},
  {"name": "advanced condensed matter physics", "code": "ph701"},
  {"name": "quantum electronics", "code": "ph703"},
  {"name": "quantum field theory and the standard\nmodel", "code": "ph705"},
  {"name": "fundamentals of robotics", "code": "ra501"},
  {"name": "artificial intelligence", "code": "ra502"},
  {"name": "robot design laboratory", "code": "ra503"},
  {"name": "programming laboratory", "code": "ra504"},
  {"name": "rural water supply and sanitation", "code": "rt504"},
  {
    "name":
        "research methodology and quantitative techniques for rural\ndevelopment",
    "code": "rt510"
  },
  {"name": "rural technology and development", "code": "rt523"},
  {"name": "introduction to sustainable polymers", "code": "sp501"},
  {"name": "polymer processing and rheology", "code": "sp502"},
  {"name": "polymer synthesis and characterization", "code": "sp503"},
  {"name": "polymer processing and rheology\nlaboratory", "code": "sp511"},
  {
    "name": "polymer synthesis and characterization\nlaboratory",
    "code": "sp512"
  },
  {"name": "chemistry", "code": "ch101"},
  {"name": "chemistry laboratory", "code": "ch110"},
  {"name": "basic electronics", "code": "ee101"},
  {"name": "mathematics - i", "code": "ma101"},
  {"name": "physics - i", "code": "ph101"},
  {"name": "physics laboratory", "code": "ph110"},
  {"name": "workshop", "code": "me110"},
  {"name": "english communication", "code": "hs101"},
  {"name": "engineering drawing", "code": "ce101"},
  {"name": "machine learning", "code": "ee526"},
  {"name": "optimization techniques", "code": "ee596h"},
  {"name": "design and analysis of algorithms", "code": "ma252"},
  {"name": "project - ii", "code": "ma499"},
  {"name": "optimization techniques", "code": "ma591"},
  {"name": "design and analysis of algorithms", "code": "ma617"},
  {"name": "approximation algorithms", "code": "ma652"},
  {"name": "differential equations", "code": "ma662"},
  {"name": "project", "code": "ma699"},
  {"name": "computational fluid dynamics", "code": "me670"},
  {"name": "measurement techniques", "code": "ph408"},
  {"name": "general physics laboratory-i", "code": "ph412"},
  {"name": "advance physics laboratory", "code": "ph516"},
  {"name": "project-ii", "code": "ph518"},
  {"name": "mini project", "code": "ph708"},
  {"name": "machine learning", "code": "ra506"},
  {"name": "analytical biotechnology lab", "code": "bt510"},
  {"name": "design project", "code": "ce402"},
  {"name": "continuum mechanics", "code": "ce501"},
  {"name": "optimization methods", "code": "ce602"},
  {"name": "project and thesis phase-i", "code": "ce690"},
  {"name": "mtech project-i", "code": "ce698"},
  {"name": "mtech project-i", "code": "ce699"},
  {"name": "fluid mechanics", "code": "cl202"},
  {"name": "computer aided numerical methods", "code": "cl502"},
  {"name": "project", "code": "cl698"},
  {"name": "computer networks", "code": "cs341"},
  {"name": "software engineering", "code": "cs441m"},
  {"name": "b tech project-i", "code": "cs498"},
  {"name": "design and analysis of algorithms", "code": "cs512"},
  {"name": "data structures lab", "code": "cs513"},
  {"name": "mathematics for computer science", "code": "cs514"},
  {"name": "data structures and algorithms", "code": "cs591h"},
  {"name": "project 1", "code": "cs698"},
  {"name": "discrete mathematics", "code": "da242"},
  {"name": "form studies", "code": "dd201"},
  {"name": "introduction to design", "code": "dd210m"},
  {"name": "interaction design", "code": "dd301"},
  {"name": "design management", "code": "dd410m"},
  {"name": "digital circuits", "code": "ee210"},
  {"name": "analog circuits", "code": "ee211m"},
  {"name": "project i", "code": "ee498"},
  {"name": "machine learning laboratory", "code": "ee524"},
  {"name": "optimization techniques", "code": "ee658"},
  {"name": "detection and estimation theory", "code": "ee692"},
  {"name": "project phase 2", "code": "em598"},
  {"name": "project 2", "code": "en698"},
  {"name": "optimization techniques", "code": "ifst006"},
  {"name": "membranes", "code": "ifst007"},
  {"name": "microbial biotechnology", "code": "ifst010"},
  {"name": "bioprocess engineering", "code": "ifst011"},
  {"name": "biosensors", "code": "ifst013"},
  {"name": "industrial wastewater pollution control", "code": "ifst014"},
  {"name": "real analysis", "code": "ma211m"},
  {"name": "discrete mathematics", "code": "ma221"},
  {"name": "scientific computing", "code": "ma311m"},
  {"name": "discrete mathematics", "code": "ma501"},
  {"name": "theory of computation", "code": "ma514"},
  {"name": "database management systems", "code": "ma518"},
  {"name": "modern algebra", "code": "ma521"},
  {"name": "linear algebra", "code": "ma522"},
  {"name": "real analysis", "code": "ma541"},
  {"name": "numerical analysis", "code": "ma572"},
  {"name": "scientific computing", "code": "ma579h"},
  {"name": "matrix computations", "code": "ma580h"},
  {"name": "statistical foundations for data science", "code": "ma589"},
  {"name": "probability theory", "code": "ma683"},
  {"name": "heat transfer", "code": "me311"},
  {"name": "btech project-i", "code": "me398"},
  {"name": "project", "code": "me401m"},
  {"name": "fluid mechanics", "code": "me520"},
  {"name": "advanced thermodynamics", "code": "me523"},
  {"name": "computational fluid dynamics", "code": "me543"},
  {"name": "semiconductor devices", "code": "ph205"},
  {"name": "statistical mechanics", "code": "ph301"},
  {"name": "engineering optics", "code": "ph305"},
  {"name": "computational physics", "code": "ph381m"},
  {"name": "classical mechanics", "code": "ph403"},
  {"name": "quantum mechanics-i", "code": "ph405"},
  {"name": "project-i", "code": "ph421"},
  {"name": "materials science and engineering", "code": "ph481m"},
  {"name": "solid state physics", "code": "ph505"},
  {"name": "computational physics", "code": "ph707"},
  {"name": "technical writing", "code": "ra507"},
  {"name": "project phase 1", "code": "ra598"},
  {"name": "project phase i", "code": "rt691"},
  {"name": "laboratory 5 reaction engineering", "code": "cl314"},
  {"code": "cl315", "name": "laboratory 6 process control"},
  {"code": "cl211", "name": "laboratory 2 heat transfer"},
  {"code": "cl210", "name": "laboratory 1 fluid mechanics"},
  {"code": "ma312", "name": "Modern Algebra"},
  {"code": "ma212", "name": "mathematical statistics"},
  {"code": "cs206", "name": "data structures and algorithms"},
  {"name": "smart systems laboratory", "code": "cs321"},
  {"name": "Social Choice and Welfare", "code": "hs251"}
];
