// COURSE CONSTANTS
export const CHANGE_COURSE = "CHANGE_COURSE";
export const EMPTY_COURSE = "EMPTY_COURSE";

// DISPLAY CONSTATNTS
export const UPDATE_FILES = "UPDATE_FILES";
export const EMPTY_FILES = "EMPTY_FILES";

// USER CONSTANTS
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
